## Надо исправить

- +Удалите из CSS аватару Кусто, ведь согласно заданию аватара грузится с сервера (у вас нет).

- Нельзя менять данные на странице до того как сервер вернул ответ. Сначала надо убедиться, что сервер вернул положительный результат, потом менять DOM. То же самое касается и окон попапов -- после сабмита формы сначала опрашиваем сервер, получаем подтверждение операции и только потом попап закрываем и вносим изменения в DOM.

- Протестируйте такой кейс: загрузите страницу, отключите сеть, попробуйте изменить данные пользователя. Попап не должен закрыться, данные на странице поменяться не должны.

- console.log('Ошибка') внутри catch -- это еще не обработка ошибки, такой catch вернет undefined, а в точке вызова этот ответ будет принят как хороший, т.к. это не объект ошибки. 

- Catch в методе Api должен либо пробрасывать ошибку через throw, либо возвращать промис с ошибкой, потому что в месте вызова метода должно быть четко понятно, что вернул Api -- успешный ответ или ошибку.

- Полученный ответ от метода экземпляра Api тоже нужно принять через then и catch.

Допустим у вас есть метод Api:

~~~
someApiMethod() {
  return fetch(...)
          .then(...)
          .catch(...) // возвращает reject
}
~~~

В точке вызова действуем так:

~~~
api.someApiMethod()
  .then(... что-то рисуем, меняем, закрываем)
  .catch(... ничего не меняем, не закрываем, сообщаем об ошибке)
~~~

- В консоли не должно быть ошибок об undefined переменных

## Можно лучше

- Реализация зума у вас, конечно, некорректная, картинки некоторые так растягивает, что не видно ничего. Рекомендую переделать с не через фоновое изображение, а через <img>

- Большое количество параметров лучше передвать в метод или в конструктор через деструктуризацию.

Например в коде:
~~~
const newClass = new Class({ windowOne, userForm, popupObj })
~~~
А внутри класса:
~~~
constructor ({ userForm, popupObj, windowOne }) {...}
~~~
И тогда порядок переменных будет неважен, это удобно

## Промежуточный итог
Сама идея Api понята верно, вы не добавили внутрь этого класса лишнего функционала, это хорошо. Исправьте критические замечения и присылайте на проверку.

## Бонус

Ваш код

getUserInfo() {
    // если тут нет связи с сервером то сразу попадаем в catch внутри класса
    return fetch('https://praktikum.tk/cohort9/users/me', this.options)
      .then(res => {
        if (res.ok) {
          return res.json();

        }
        // А этот reject ведет нас уже в catch в точку вызова, а не в тот, что ниже
        // Сервер то ответ дал, просто плохой
        return Promise.reject(`Ошибка: ${res.status}`); 

      })
      .catch(err => {
        // А тут надо добавить возврат ошибки, чтобы в точке вызова мы тоже попапли в catch
        console.log(err);
      })
